#' GitHub network plot
#' 
#' Generate an interactive network plot for all repositories 
#' in a GitHub Organization, where users and repositories are nodes and
#'  contributions are edges.
#' Edge width is proportional to the number of contributions 
#'  each user made to a given repository.
#' User nodes use images automatically pulled from 
#'  their respective GitHub profile.
#' Repo node size is proportional the size of the repository.
#' @param graph An \link[igraph]{graph} generated by 
#'  \link[SkillNet]{github_network}.  
#' @param show_plot A named list with two items:
#' \itemize{
#' \item{r}{Whether to show the dependency graph in R/Rstudio
#' (will \emph{not} show user-specific \code{background} color)}.
#' \item{browser}{Whether to show the dependency graph in default web browser
#' (will show user-specific \code{background} color)}.
#' }
#' @param save_path Path to save the plot to, as an interactive,
#'  self-container HTML file.
#' @param verbose Print messages.
#' @inheritParams visNetwork::visNodes
#' @inheritParams visNetwork::visSave
#' @inheritParams visNetwork::visOptions 
#' @inheritParams visNetwork::visIgraphLayout
#' @export
#' @importFrom visNetwork visIgraph visIgraphLayout visNodes visEdges 
#' @importFrom visNetwork visInteraction visSave
#' @importFrom utils browseURL
#' @importFrom methods show
#' @examples 
#' g <- github_network(org = "neurogenomics")
#' vis <- github_network_plot(graph = g$graph)
github_network_plot <- function(graph,
                                shape = c("image", "hexagon"),
                                layout = "layout_nicely",
                                physics = FALSE,
                                show_plot = list(r=TRUE,
                                                 browser=TRUE),
                                save_path = NULL,
                                width = NULL,
                                height = NULL,
                                background = "white",
                                verbose = TRUE){  
    
    vis <- visNetwork::visIgraph(graph) |>
        visNetwork::visIgraphLayout(layout = layout,
                                    physics = physics) |>
        visNetwork::visNodes(
            shape =  tolower(shape[1]),
            borderWidth = 2,
            # image = "image",#image,
            labelHighlightBold = TRUE,
            color = list(
                background =  "#25355c",
                border = "#41c6c8",
                highlight = "#56ffff",
                hover=list(background="blue",
                           border="#41c6c8")
            ),
            font = list(color="white",
                        # size=20,
                        face="Tahoma",
                        strokeWidth=10,
                        strokeColor="rgba(103,115,141,.5)"),
            shadow = list(enabled = TRUE,
                          # size = 40,
                          color="#537bcb") # "#03b1f0"
        ) |>
        visNetwork::visEdges(
            arrows = 'to',
            shadow = list(enabled=TRUE,color="#686ea6"),
            smooth = TRUE,dashes =FALSE,
            width = "100%",
            color = list(color = "#686ea6",
                         opacity=.75,
                         highlight = "#56ffff"),
        ) |>
        # visNetwork::visOptions(nodesIdSelection = list(enabled = FALSE,
        #                                                selected=pkg_name,
        #                                                main="select package"),
        #                        highlightNearest=TRUE,
        #                        width = width,
        #                        height = height) |>
        visNetwork::visInteraction(
            tooltipStyle =paste(
                "position: fixed",
                "visibility: hidden",
                "font-family: Tahoma",
                "background-color: rgba(0,0,0,.5)",
                "box-shadow: 2px 2px 2px 3px rgba(247, 247, 247, 0.5)",
                "color: #fff",
                "padding: 10px",
                sep=";"))
    #### Save ####
    if(!is.null(save_path)) {
        message("Saving dependency graph plot ==> ",save_path)
        ## Ensure .html suffix
        save_path <- paste0(gsub("\\.html","",save_path),".html")
        dir.create(dirname(save_path),showWarnings = FALSE,recursive = TRUE)
        visNetwork::visSave(graph = vis,
                            file = save_path,
                            background = background,
                            selfcontained = TRUE)
    }
    #### Show ####
    if(isTRUE(show_plot$r)) {
        messager("Showing plot in R.",v=verbose)
        methods::show(vis)
    }
    if(isTRUE(show_plot$browser) && (!is.null(save_path))){ 
        if(file.exists(save_path)){
            messager("Showing plot in browser.",v=verbose)
            utils::browseURL(save_path)
        } 
    }
    return(vis)
}
